name: trigger-testing
on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    name: Test check
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0